Repository KratosMultiphysics/GiDInterface, pull requests merged in 2018-06, with the labels that each got.

#376 [Release 6.0]Do not write CONDENSED_DOF_LIST as post process variable
  kratos.gid/apps/Structural/xml/GetFromXML.tcl
Labels: Release

#386 Corrections for the Release Solid App
  kratos.gid/apps/Solid/examples/CircularTank.tcl
  kratos.gid/apps/Solid/examples/EccentricColumn.tcl
  kratos.gid/apps/Solid/xml/GetFromXML.tcl
  kratos.gid/scripts/Model/Solver.tcl
Labels: Release

#388 Missing hyperelastic laws in strucural
  kratos.gid/apps/Structural/xml/ConstitutiveLaws.xml
Labels: Release

#392 Adding a Damage example in 2D
  kratos.gid/apps/Solid/examples/NotchedBeam.tcl
  kratos.gid/apps/Solid/examples/NotchedBeam2D.gid/NotchedBeam2D.geo
  kratos.gid/apps/Solid/examples/NotchedBeam2D.gid/NotchedBeam2D.prj
  kratos.gid/apps/Solid/examples/NotchedBeam2D.gid/NotchedBeam2D.vv
  kratos.gid/apps/Solid/examples/examples.tcl
  kratos.gid/apps/Solid/images/Black/notched_example.png
  kratos.gid/apps/Solid/images/notched_example.png
  kratos.gid/apps/Solid/start.tcl
Labels: Release

#363 Updating FSI main script to use Kratos Model in structure solver
  kratos.gid/apps/FSI/python/KratosFSI.py
Labels: After release 6, bug

#398 [FSI] FSI upgrade in accordance to stage requirements
  kratos.gid/apps/FSI/python/KratosFSI.py
  kratos.gid/apps/FSI/write/writeProjectParameters.tcl
  kratos.gid/apps/FSI/xml/Strategies.xml
  kratos.gid/apps/Fluid/write/writeProjectParameters.tcl
Labels: enhancement
