Repository KratosMultiphysics/GiDInterface, pull requests merged in 2018-05, with the labels that each got.

#345 [FSI] Hotfix: correcting application imports
  kratos.gid/apps/FSI/python/KratosFSI.py
Labels: bug

#361 Optional parameters protection #360
  kratos.gid/scripts/Writing.tcl
Labels: Release

#371 [Hotfix] [FluidDynamics] Supressing debug print
  kratos.gid/apps/Fluid/write/write.tcl
Labels: Release, clean up
