Repository KratosMultiphysics/GiDInterface, pull requests merged in 2018-03, with the labels that each got.

#271 Fixes #270 and KratosMultiphysics/Kratos#1578
  kratos.gid/scripts/Writing.tcl
Labels: bug

#281 Feature fsi turek example
  kratos.gid/apps/EmbeddedFluid/python/KratosFluid.py
  kratos.gid/apps/FSI/examples/TurekBenchmark.tcl
  kratos.gid/apps/FSI/examples/examples.tcl
  kratos.gid/apps/FSI/python/KratosFSI.py
  kratos.gid/apps/FSI/start.tcl
Labels: new feature

#291 Fix dem example parameters
  kratos.gid/apps/DEM/examples/SpheresDrop.tcl
Labels: enhancement

#296 Addition of Bbar element and J2 constitutive model to the interface
  kratos.gid/apps/Structural/xml/ConstitutiveLaws.xml
  kratos.gid/apps/Structural/xml/Elements.xml
  kratos.gid/apps/Structural/xml/Materials.xml
Labels: Release 5.3, enhancement, help wanted, new feature

#301 Add Point Moment for 3D #227
  kratos.gid/apps/Structural/xml/Conditions.xml
Labels: Release 5.3, enhancement

#305 Feature add eigensolveranalysis
  kratos.gid/apps/Structural/write/writeProjectParameters.tcl
  kratos.gid/apps/Structural/xml/GetFromXML.tcl
  kratos.gid/apps/Structural/xml/Loads.spd
  kratos.gid/apps/Structural/xml/NodalConditions.xml
  kratos.gid/apps/Structural/xml/Procs.spd
  kratos.gid/apps/Structural/xml/SolutionStrategy.spd
  kratos.gid/apps/Structural/xml/Solvers.xml
  kratos.gid/apps/Structural/xml/StageInfo.spd
  kratos.gid/apps/Structural/xml/Strategies.xml
  kratos.gid/scripts/Model/SolutionStrategy.tcl
  kratos.gid/scripts/Model/Solver.tcl
  kratos.gid/scripts/Writing.tcl
  kratos.gid/scripts/spdAuxiliar.tcl
Labels: Release 5.3, new feature
