Repository KratosMultiphysics/GiDInterface, pull requests merged in 2018-12, with the labels that each got.

#494 Add modelpart name Fluid embedded
  kratos.gid/apps/EmbeddedFluid/write/write.tcl
Labels: bug

#496 [Mpm] New axis element interface
  kratos.gid/apps/MPM/images/2Da.png
  kratos.gid/apps/MPM/start.tcl
  kratos.gid/apps/MPM/write/writeProjectParameters.tcl
  kratos.gid/apps/MPM/xml/Conditions.xml
  kratos.gid/apps/MPM/xml/ConstitutiveLaws.xml
  kratos.gid/apps/MPM/xml/Elements.xml
  kratos.gid/apps/MPM/xml/StageInfo.spd
Labels: help wanted, new feature

#500 [Mpm] Particle per element inside element
  kratos.gid/apps/MPM/write/writeProjectParameters.tcl
  kratos.gid/apps/MPM/xml/ConstitutiveLaws.xml
  kratos.gid/apps/MPM/xml/Elements.xml
  kratos.gid/apps/MPM/xml/GetFromXML.tcl
Labels: enhancement, help wanted

#493 Add bfs cht
  kratos.gid/apps/ConjugateHeatTransfer/examples/BFS.tcl
  kratos.gid/apps/ConjugateHeatTransfer/examples/examples.tcl
  kratos.gid/apps/ConjugateHeatTransfer/start.tcl
  kratos.gid/apps/ConjugateHeatTransfer/write/writeProjectParameters.tcl
  kratos.gid/apps/ConvectionDiffusion/write/writeProjectParameters.tcl
Labels: new feature
