Repository KratosMultiphysics/GiDInterface, pull requests merged in 2019-11, with the labels that each got.

#667 Feature optimization mdpa
  kratos.gid/apps/Structural/write/write.tcl
  kratos.gid/kratos.tcl
  kratos.gid/scripts/Controllers/Preferences.xml
  kratos.gid/scripts/Controllers/PreferencesWindow.tcl
  kratos.gid/scripts/Writing/WriteConditions.tcl
  kratos.gid/scripts/Writing/WriteConditionsByGiDId.tcl
  kratos.gid/scripts/Writing/WriteConditionsByUniqueId.tcl
  kratos.gid/scripts/Writing/WriteNodes.tcl
  kratos.gid/scripts/Writing/WriteSubModelPart.tcl
  kratos.gid/scripts/Writing/Writing.tcl
Labels: enhancement

#664 [DEM]add initial conditions 2d/3d
  kratos.gid/apps/CDEM/write/writeMDPA_Parts.tcl
  kratos.gid/apps/CDEM/write/writeMDPA_Walls.tcl
  kratos.gid/apps/CDEM/write/writeProjectParameters.tcl
  kratos.gid/apps/CDEM/xml/ConstitutiveLawsC.xml
  kratos.gid/apps/CDEM/xml/MaterialsC.xml
  kratos.gid/apps/DEM/write/writeMDPA_Parts.tcl
  kratos.gid/apps/DEM/write/writeMDPA_Walls.tcl
  kratos.gid/apps/DEM/write/writeProjectParameters.tcl
  kratos.gid/apps/DEM/xml/Conditions.xml
  kratos.gid/apps/DEM/xml/Materials.xml
  kratos.gid/apps/DEM/xml/Processes.xml
Labels: enhancement

#671 [CDEM] Added procedure to create and assign bonded domains to all volumes
  kratos.gid/apps/CDEM/examples/examples.tcl
  kratos.gid/apps/CDEM/images/stone.png
  kratos.gid/apps/CDEM/start.tcl
  kratos.gid/apps/CDEM/xml/BulkGroup.tcl
Labels: new feature

#673 [PfemFluid] changes in dependencies
  kratos.gid/apps/Pfem/xml/NodalConditions.xml
  kratos.gid/apps/Pfem/xml/Processes.xml
  kratos.gid/apps/PfemFluid/images/exampleFluid.png
  kratos.gid/apps/PfemFluid/images/exampleFsi.png
  kratos.gid/apps/PfemFluid/python/Erase--script.py
  kratos.gid/apps/PfemFluid/python/RunPFEM.py
  kratos.gid/apps/PfemFluid/start.tcl
  kratos.gid/apps/PfemFluid/write/ProjectParameters.json
  kratos.gid/apps/PfemFluid/write/write.tcl
  kratos.gid/apps/PfemFluid/write/writeProjectParameters.tcl
  kratos.gid/apps/PfemFluid/xml/Elements.xml
  kratos.gid/apps/PfemFluid/xml/Main.spd
  kratos.gid/apps/PfemFluid/xml/NodalConditions.xml
  kratos.gid/apps/PfemFluid/xml/Strategies.xml
  kratos.gid/apps/PfemFluid/xml/XmlController.tcl
Labels: enhancement

#674 Create LICENSE.md
  LICENSE.md
Labels: question

#681 nodal_nonhistorical_results as default
  kratos.gid/scripts/Writing/WriteProjectParameters.tcl
Labels: enhancement
