Repository KratosMultiphysics/GiDInterface, pull requests merged in 2019-05, with the labels that each got.

#562 Fix structural example 3d
  kratos.gid/apps/Structural/examples/examples.tcl
  kratos.gid/apps/Structural/start.tcl
Labels: enhancement

#587 Fix write custom submodelpart by unique id
  kratos.gid/apps/Fluid/write/write.tcl
  kratos.gid/scripts/Writing/WriteConditionsByUniqueId.tcl
  kratos.gid/scripts/Writing/WriteSubModelPart.tcl
Labels: bug

#591 Conditions on Contact Structural
  kratos.gid/apps/Structural/write/write.tcl
  kratos.gid/scripts/Writing/WriteConditions.tcl
Labels: enhancement

#585 [WIP] Make vtk-output optional
  kratos.gid/apps/Buoyancy/examples/HeatedSquare.tcl
  kratos.gid/apps/Common/xml/Results.spd
  kratos.gid/apps/ConjugateHeatTransfer/examples/BFS.tcl
  kratos.gid/apps/ConjugateHeatTransfer/examples/HeatedSquare.tcl
  kratos.gid/apps/ConjugateHeatTransfer/examples/cylinder_cooling.tcl
  kratos.gid/apps/ConvectionDiffusion/examples/HeatedSquare.tcl
  kratos.gid/apps/ConvectionDiffusion/xml/GetFromXML.tcl
  kratos.gid/apps/EmbeddedFluid/examples/CylinderInFlow.tcl
  kratos.gid/apps/EmbeddedFluid/xml/GetFromXML.tcl
  kratos.gid/apps/FSI/examples/HighRiseBuilding.tcl
  kratos.gid/apps/FSI/examples/MokChannelWithFlexibleWall.tcl
  kratos.gid/apps/FSI/examples/TurekBenchmark.tcl
  kratos.gid/apps/Fluid/examples/CylinderInFlow.tcl
  kratos.gid/apps/Fluid/examples/HighRiseBuilding.tcl
  kratos.gid/apps/Fluid/xml/GetFromXML.tcl
  kratos.gid/apps/FluidDEM/xml/GetFromXML.tcl
  kratos.gid/apps/PotentialFluid/examples/NACA0012.tcl
  kratos.gid/apps/Structural/xml/GetFromXML.tcl
  kratos.gid/scripts/Writing/WriteProjectParameters.tcl
  kratos.gid/scripts/Writing/Writing.tcl
Labels: enhancement, help wanted

#595 Feature non newtonian fluid
  kratos.gid/apps/Fluid/xml/ConstitutiveLaws.xml
  kratos.gid/apps/Fluid/xml/GetFromXML.tcl
  kratos.gid/scripts/Model/ConstitutiveLaw.tcl
Labels: new feature

#596 Feature add logs
  kratos.gid/kratos.tcl
  kratos.gid/scripts/Applications.tcl
  kratos.gid/scripts/Controllers/ApplicationMarketWindow.tcl
  kratos.gid/scripts/Controllers/TreeInjections.tcl
  kratos.gid/scripts/Logs.tcl
  kratos.gid/scripts/Writing/WriteProjectParameters.tcl
Labels: new feature

#449 [Do not merge yet] New event system + minimum gid version
  kratos.gid/apps/Buoyancy/write/writeProjectParameters.tcl
  kratos.gid/apps/CDEM/write/writeProjectParameters.tcl
  kratos.gid/apps/Fluid/examples/CylinderInFlow.tcl
  kratos.gid/apps/Fluid/examples/HighRiseBuilding.tcl
  kratos.gid/kratos.tcl
  kratos.gid/kratos.xml
  kratos.gid/scripts/Applications.tcl
  kratos.gid/scripts/DeprecatedEvents.tcl
  kratos.gid/scripts/Utils.tcl
Labels: enhancement
