Repository KratosMultiphysics/GiDInterface, pull requests merged in 2019-01, with the labels that each got.

#502 adding basic vtk-output
  kratos.gid/scripts/Writing/WriteProjectParameters.tcl
Labels: new feature

#507 [ConvDiff] CHT interface cleanup and BFS example fix
  kratos.gid/apps/ConjugateHeatTransfer/examples/BFS.tcl
  kratos.gid/apps/ConjugateHeatTransfer/examples/HeatedSquare.tcl
  kratos.gid/apps/ConjugateHeatTransfer/write/writeProjectParameters.tcl
  kratos.gid/apps/ConjugateHeatTransfer/xml/Conditions.xml
  kratos.gid/apps/ConjugateHeatTransfer/xml/GetFromXML.tcl
  kratos.gid/apps/ConjugateHeatTransfer/xml/SolutionStrategy.spd
Labels: bug, enhancement

#511 [HOTFIX] Feature cht apply heat transfer interface process
  kratos.gid/apps/ConjugateHeatTransfer/examples/BFS.tcl
  kratos.gid/apps/ConjugateHeatTransfer/examples/HeatedSquare.tcl
  kratos.gid/apps/ConjugateHeatTransfer/xml/Conditions.xml
  kratos.gid/apps/ConjugateHeatTransfer/xml/GetFromXML.tcl
  kratos.gid/apps/ConjugateHeatTransfer/xml/Processes.xml
  kratos.gid/apps/ConvectionDiffusion/examples/HeatedSquare.tcl
  kratos.gid/apps/MPM/xml/GetFromXML.tcl
Labels: bug
