Repository KratosMultiphysics/GiDInterface, pull requests merged in 2019-12, with the labels that each got.

#682 non historical thing is not valid for vtk
  kratos.gid/scripts/Writing/WriteProjectParameters.tcl
Labels: bug

#684 Feature/dem allow line in demfemwalls
  kratos.gid/apps/DEM/write/writeMDPA_Walls.tcl
  kratos.gid/apps/DEM/xml/Conditions.xml
  kratos.gid/scripts/Writing/WriteConditionsByGiDId.tcl
Labels: enhancement

#676 Failure criterion state printed for CDEM
  kratos.gid/apps/CDEM/write/writeProjectParameters.tcl
  kratos.gid/apps/CDEM/xml/Conditions.xml
  kratos.gid/apps/CDEM/xml/Processes.xml
  kratos.gid/apps/CDEM/xml/Results.spd
  kratos.gid/apps/CDEM/xml/XmlController.tcl
  kratos.gid/apps/DEM/xml/Conditions.xml
  kratos.gid/apps/DEM/xml/Processes.xml
  kratos.gid/apps/DEM/xml/Results.spd
  kratos.gid/apps/DEM/xml/XmlController.tcl
  kratos.gid/kratos.unix.bat
Labels: new feature

#685 [DEM] cdem fix 2d/3d conditions. under revision, not to be merged yet.
  kratos.gid/apps/CDEM/write/writeMDPA_Parts.tcl
  kratos.gid/apps/CDEM/write/writeMDPA_Walls.tcl
  kratos.gid/apps/DEM/write/writeMDPA_Parts.tcl
  kratos.gid/apps/DEM/write/writeMDPA_Walls.tcl
  kratos.gid/apps/DEM/xml/Processes.xml
Labels: DO NOT MERGE YET

#696 Hotfix dem inertia
  kratos.gid/apps/DEM/write/writeMDPA_Walls.tcl
  kratos.gid/apps/DEM/xml/Processes.xml
  kratos.gid/apps/DEM/xml/XmlController.tcl
  kratos.gid/scripts/Controllers/CommonProcs.tcl
  kratos.gid/scripts/Controllers/MdpaImportMesh.tcl
  kratos.gid/scripts/Controllers/TreeInjections.tcl
  kratos.gid/scripts/Model/Parameter.tcl
Labels: bug
