Repository KratosMultiphysics/GiDInterface, pull requests merged in 2019-03, with the labels that each got.

#528 [ConvDiff] Example intervals fix
  kratos.gid/apps/ConvectionDiffusion/examples/HeatedSquare.tcl
Labels: bug

#532 [FSI] Mesh motion output and mok fix
  kratos.gid/apps/FSI/examples/MokChannelWithFlexibleWall.tcl
  kratos.gid/apps/FSI/xml/GetFromXML.tcl
Labels: bug, new feature

#535 Add missing proc
  kratos.gid/apps/DEMPFEM/xml/Procs.spd
Labels: bug

#536 [Buoyancy] Example case as reference test in literature
  kratos.gid/apps/Buoyancy/examples/HeatedSquare.tcl
  kratos.gid/apps/Buoyancy/xml/ConstitutiveLaws.xml
Labels: bug, enhancement

#537 [Structural] Kratos name correction
  kratos.gid/apps/Structural/xml/ConstitutiveLaws.xml
Labels: bug

#538 [Buoyancy] Minor changes to reach steady state
  kratos.gid/apps/Buoyancy/examples/HeatedSquare.tcl
  kratos.gid/apps/Buoyancy/start.tcl
Labels: enhancement

#542 [ConvDiff] Enhance predefined example & logo
  kratos.gid/apps/ConvectionDiffusion/examples/HeatedSquare.tcl
  kratos.gid/apps/ConvectionDiffusion/images/logo.png
Labels: enhancement

#545 Add materials to convection diffusion in CHT
  kratos.gid/apps/ConjugateHeatTransfer/xml/Main.spd
Labels: bug

#548 [Fluid] Example intervals hotfix
  kratos.gid/apps/Fluid/examples/CylinderInFlow.tcl
Labels: bug

#547 [CHT] New cylinder example (and logo)
  kratos.gid/apps/ConjugateHeatTransfer/examples/cylinder_cooling.tcl
  kratos.gid/apps/ConjugateHeatTransfer/examples/examples.tcl
  kratos.gid/apps/ConjugateHeatTransfer/images/logo.png
  kratos.gid/apps/ConjugateHeatTransfer/start.tcl
Labels: enhancement, new feature

#550 [CHT] BFS minor fixes
  kratos.gid/apps/ConjugateHeatTransfer/examples/BFS.tcl
Labels: bug

#555 [FSI] Turek benchmark settings
  kratos.gid/apps/FSI/examples/TurekBenchmark.tcl
Labels: enhancement

#559 [Solid] fix beam schemes for static and quasi-static and section name
  kratos.gid/apps/Solid/examples/StaticBeamLattice.gid/StaticBeamLattice.geo
  kratos.gid/apps/Solid/examples/StaticBeamLattice.gid/StaticBeamLattice.prj
  kratos.gid/apps/Solid/examples/StaticBeamLattice.gid/StaticBeamLattice.vv
  kratos.gid/apps/Solid/examples/StaticBeamLattice.tcl
  kratos.gid/apps/Solid/examples/examples.tcl
  kratos.gid/apps/Solid/images/lattice_example.png
  kratos.gid/apps/Solid/start.tcl
  kratos.gid/apps/Solid/write/writeProjectParameters.tcl
  kratos.gid/apps/Solid/xml/ConstitutiveLaws.xml
  kratos.gid/apps/Solid/xml/StageInfo.spd
  kratos.gid/apps/Solid/xml/Strategies.xml
Labels: bug, enhancement

#552 [DEM]Add fluid dem application
  kratos.gid/apps/DEM/images/black1.png
  kratos.gid/apps/DEM/images/piec.png
  kratos.gid/apps/DEM/start.tcl
  kratos.gid/apps/DEM/write/write.tcl
  kratos.gid/apps/DEM/write/writeMDPA_Walls.tcl
  kratos.gid/apps/DEM/write/writeProjectParameters.tcl
  kratos.gid/apps/DEM/write/write_utils.tcl
  kratos.gid/apps/DEM/xml/Conditions.spd
  kratos.gid/apps/DEM/xml/Graphs.spd
  kratos.gid/apps/DEM/xml/Gravity.spd
  kratos.gid/apps/DEM/xml/Processes.xml
  kratos.gid/apps/DEM/xml/Results.spd
  kratos.gid/apps/DEM/xml/SolutionStrategy.spd
  kratos.gid/apps/DEM/xml/StageInfo.spd
  kratos.gid/apps/DEMLauncher/start.tcl
  kratos.gid/apps/DEMPFEM/write/writeProjectParameters.tcl
  kratos.gid/apps/Fluid/write/write.tcl
  kratos.gid/apps/FluidDEM/images/logo.png
  kratos.gid/apps/FluidDEM/images/therm.png
  kratos.gid/apps/FluidDEM/python/MainKratos.py
  kratos.gid/apps/FluidDEM/start.tcl
  kratos.gid/apps/FluidDEM/write/write.tcl
  kratos.gid/apps/FluidDEM/write/writeProjectParameters.tcl
  kratos.gid/apps/FluidDEM/xml/Elements.xml
  kratos.gid/apps/FluidDEM/xml/GetFromXML.tcl
  kratos.gid/apps/FluidDEM/xml/Main.spd
  kratos.gid/apps/FluidDEM/xml/Procs.spd
  kratos.gid/apps/FluidDEM/xml/TimeParameters.spd
  kratos.gid/apps/FluidLauncher/start.tcl
  kratos.gid/kratos_default.spd
  kratos.gid/scripts/Controllers/TreeInjections.tcl
Labels: new feature

#560 [PotentialFlowApplication] Working again
  kratos.gid/apps/Fluid/write/write.tcl
  kratos.gid/apps/Fluid/write/writeProjectParameters.tcl
  kratos.gid/apps/PotentialFluid/examples/NACA0012.tcl
  kratos.gid/apps/PotentialFluid/examples/examples.tcl
  kratos.gid/apps/PotentialFluid/python/KratosPotentialFlow.py
  kratos.gid/apps/PotentialFluid/python/KratosPotentialFluid.py
  kratos.gid/apps/PotentialFluid/start.tcl
  kratos.gid/apps/PotentialFluid/write/write.tcl
  kratos.gid/apps/PotentialFluid/write/writeProjectParameters.tcl
  kratos.gid/apps/PotentialFluid/xml/Conditions.xml
  kratos.gid/apps/PotentialFluid/xml/Elements.xml
  kratos.gid/apps/PotentialFluid/xml/Main.spd
  kratos.gid/apps/PotentialFluid/xml/NodalConditions.xml
  kratos.gid/apps/PotentialFluid/xml/Processes.xml
Labels: bug
