Repository KratosMultiphysics/GiDInterface, pull requests merged in 2020-12, with the labels that each got.

#781 Feature/increase logs
  kratos.gid/apps/FSI/examples/examples.tcl
  kratos.gid/apps/FSI/start.tcl
  kratos.gid/kratos.tcl
  kratos.gid/scripts/Controllers/Preferences.xml
  kratos.gid/scripts/Controllers/PreferencesWindow.tcl
  kratos.gid/scripts/Logs.tcl
  kratos.gid/scripts/Menus.tcl
  kratos.gid/scripts/Utils.tcl
  kratos.gid/scripts/Writing/Writing.tcl
Labels: new feature

#784 Changes to version 8
  kratos.gid/apps/CDEM/xml/XmlController.tcl
  kratos.gid/apps/Common/xml/Solvers.xml
  kratos.gid/apps/DEM/xml/StageInfo.spd
  kratos.gid/apps/DEM/xml/Strategies.xml
  kratos.gid/apps/EmbeddedFluid/write/writeProjectParameters.tcl
  kratos.gid/apps/EmbeddedFluid/xml/Strategies.xml
  kratos.gid/apps/FSI/examples/examples.xml
  kratos.gid/apps/FSI/images/HighRiseBuilding.png
  kratos.gid/apps/Fluid/write/writeProjectParameters.tcl
  kratos.gid/apps/Fluid/xml/Elements.xml
  kratos.gid/apps/Fluid/xml/Strategies.xml
  kratos.gid/apps/FluidDEM/examples/CylinderInFlow.tcl
  kratos.gid/apps/FluidDEM/write/writeProjectParameters.tcl
  kratos.gid/apps/FluidDEM/xml/Elements.xml
  kratos.gid/apps/FluidDEM/xml/Strategies.xml
  kratos.gid/apps/FluidDEM/xml/XmlController.tcl
  kratos.gid/kratos.xml
  kratos.gid/kratos_default.spd
  kratos.gid/scripts/Controllers/CommonProcs.tcl
  kratos.gid/scripts/Model/Model.tcl
  kratos.gid/scripts/Model/SolutionStrategy.tcl
Labels: enhancement

#788 [Fluid] Fluid fixes and weakly compressible element addition
  kratos.gid/apps/Buoyancy/xml/ConstitutiveLaws.xml
  kratos.gid/apps/Buoyancy/xml/Materials.xml
  kratos.gid/apps/Fluid/write/writeProjectParameters.tcl
  kratos.gid/apps/Fluid/xml/ConstitutiveLaws.xml
  kratos.gid/apps/Fluid/xml/Elements.xml
  kratos.gid/apps/Fluid/xml/Materials.xml
  kratos.gid/apps/Fluid/xml/Strategies.xml
  kratos.gid/apps/FluidDEM/xml/Elements.xml
Labels: bug, enhancement
