Repository KratosMultiphysics/GiDInterface, pull requests merged in 2020-11, with the labels that each got.

#762 bugfix DEM 2d Circle mesher
  kratos.gid/apps/DEM/examples/CirclesDrop.tcl
Labels: bug

#769 Hotfix -> Gauss point result hidden in some apps like Structural
  kratos.gid/scripts/Controllers/TreeInjections.tcl
Labels: bug

#767 [Fluid] Export new elements to GUI
  kratos.gid/apps/Fluid/write/writeProjectParameters.tcl
  kratos.gid/apps/Fluid/xml/AnalysisType.spd
  kratos.gid/apps/Fluid/xml/Elements.xml
  kratos.gid/apps/Fluid/xml/Parts.spd
  kratos.gid/apps/Fluid/xml/Procs.spd
  kratos.gid/apps/Fluid/xml/Strategies.xml
  kratos.gid/apps/Fluid/xml/XmlController.tcl
Labels: help wanted, new feature

#729 split child from parent group by - instead of /
  kratos.gid/scripts/Writing/Writing.tcl
Labels: enhancement
