Repository KratosMultiphysics/GiDInterface, pull requests merged in 2020-01, with the labels that each got.

#697 Hotfix dem customsmp
  kratos.gid/apps/DEM/start.tcl
  kratos.gid/apps/DEM/write/writeMDPA_Parts.tcl
  kratos.gid/apps/DEM/xml/Conditions.xml
  kratos.gid/apps/DEM/xml/Processes.xml
  kratos.gid/apps/DEM/xml/XmlController.tcl
  kratos.gid/scripts/Writing/WriteElements.tcl
Labels: DO NOT MERGE YET, enhancement, help wanted

#710 Pfem fluid submodelpart names
  kratos.gid/apps/PfemFluid/write/write.tcl
  kratos.gid/apps/PfemFluid/write/writeProjectParameters.tcl
Labels: bug

#709 Conditions parameters - missing clausule
  kratos.gid/scripts/Controllers/CommonProcs.tcl
Labels: bug

#706 [DEM] tree changes
  kratos.gid/apps/CDEM/write/writeProjectParameters.tcl
  kratos.gid/apps/CDEM/xml/Main.spd
  kratos.gid/apps/CDEM/xml/PartsCont.spd
  kratos.gid/apps/CDEM/xml/SolutionStrategy.spd
  kratos.gid/apps/DEM/xml/Conditions.xml
  kratos.gid/apps/DEM/xml/Main.spd
  kratos.gid/apps/DEM/xml/Parts.spd
  kratos.gid/apps/DEM/xml/Processes.xml
  kratos.gid/apps/DEM/xml/Results.spd
  kratos.gid/apps/DEM/xml/SolutionStrategy.spd
Labels: enhancement
