Repository KratosMultiphysics/GiDInterface, pull requests merged in 2020-02, with the labels that each got.

#680 Feature mpm 2D example
  kratos.gid/apps/MPM/examples/FallingSandBall.tcl
  kratos.gid/apps/MPM/examples/examples.tcl
  kratos.gid/apps/MPM/start.tcl
  kratos.gid/apps/MPM/write/write.tcl
  kratos.gid/apps/MPM/write/writeProjectParameters.tcl
  kratos.gid/apps/MPM/xml/XmlController.tcl
Labels: enhancement

#716 Feature/small displacement loads
  kratos.gid/apps/Structural/start.tcl
  kratos.gid/apps/Structural/write/write.tcl
  kratos.gid/apps/Structural/xml/Conditions.xml
  kratos.gid/apps/Structural/xml/Elements.xml
  kratos.gid/scripts/Model/Model.tcl
  kratos.gid/scripts/Model/Topology.tcl
  kratos.gid/scripts/Writing/WriteConditions.tcl
Labels: enhancement

#717 Pfem/materials file
  kratos.gid/apps/PfemFluid/write/write.tcl
  kratos.gid/apps/PfemFluid/write/writeProjectParameters.tcl
Labels: enhancement

#718 [Structural] Mixed u-vol_ strain element addition
  kratos.gid/apps/Structural/examples/examples.tcl
  kratos.gid/apps/Structural/examples/incompressible_cook_membrane.tcl
  kratos.gid/apps/Structural/start.tcl
  kratos.gid/apps/Structural/write/writeProjectParameters.tcl
  kratos.gid/apps/Structural/xml/Elements.xml
  kratos.gid/apps/Structural/xml/NodalConditions.xml
  kratos.gid/apps/Structural/xml/XmlController.tcl
Labels: new feature

#720 Change dependency system to TCL proc only
  kratos.gid/scripts/Controllers/CommonProcs.tcl
  kratos.gid/scripts/Controllers/TreeInjections.tcl
  kratos.gid/scripts/Model/Element.tcl
  kratos.gid/scripts/Model/Parameter.tcl
Labels: bug

#722 Add Dam application
  kratos.gid/apps/DEM/write/write_utils.tcl
  kratos.gid/apps/Dam/examples/ThermoMechaDam.tcl
  kratos.gid/apps/Dam/examples/examples.tcl
  kratos.gid/apps/Dam/images/elliptical.png
  kratos.gid/apps/Dam/images/logo.png
  kratos.gid/apps/Dam/images/parabolic.png
  kratos.gid/apps/Dam/python/MainKratosDam.py
  kratos.gid/apps/Dam/python/dam_acoustic_script.py
  kratos.gid/apps/Dam/python/dam_eigen_script.py
  kratos.gid/apps/Dam/python/dam_main.py
  kratos.gid/apps/Dam/python/dam_main_construction.py
  kratos.gid/apps/Dam/python/dam_main_selfweight.py
  kratos.gid/apps/Dam/start.tcl
  kratos.gid/apps/Dam/write/write.tcl
  kratos.gid/apps/Dam/write/writeProjectParameters.tcl
  kratos.gid/apps/Dam/xml/Conditions.xml
  kratos.gid/apps/Dam/xml/ConstitutiveLaws.xml
  kratos.gid/apps/Dam/xml/DirichletBoundaryConditions.spd
  kratos.gid/apps/Dam/xml/Elements.xml
  kratos.gid/apps/Dam/xml/GetFromXML.tcl
  kratos.gid/apps/Dam/xml/Loads.spd
  kratos.gid/apps/Dam/xml/Main.spd
  kratos.gid/apps/Dam/xml/Materials.spd
  kratos.gid/apps/Dam/xml/Materials.xml
  kratos.gid/apps/Dam/xml/ModelInfo.spd
  kratos.gid/apps/Dam/xml/NodalConditions.xml
  kratos.gid/apps/Dam/xml/Parts.spd
  kratos.gid/apps/Dam/xml/Processes.xml
  kratos.gid/apps/Dam/xml/Procs.spd
  kratos.gid/apps/Dam/xml/Results.spd
  kratos.gid/apps/Dam/xml/Solution.spd
  kratos.gid/apps/Dam/xml/Solvers.xml
  kratos.gid/apps/Dam/xml/Strategies.xml
  kratos.gid/apps/Dam/xml/ThermalLoads.spd
  kratos.gid/apps/Dam/xml/Utilities.spd
  kratos.gid/kratos_default.spd
  kratos.gid/scripts/Writing/WriteProcess.tcl
  kratos.gid/scripts/Writing/WriteProjectParameters.tcl
Labels: new feature

#725 [Hotfix][Structural] Reverting DISPLACEMENT nodal conditions
  kratos.gid/apps/Structural/xml/NodalConditions.xml
Labels: bug

#726 Feature/dam example 3d
  kratos.gid/apps/Dam/examples/ThermoMechaDam2D.tcl
  kratos.gid/apps/Dam/examples/ThermoMechaDam3D.tcl
  kratos.gid/apps/Dam/examples/examples.tcl
  kratos.gid/apps/Dam/start.tcl
  kratos.gid/scripts/Controllers/TreeInjections.tcl
Labels: new feature

#727 Feature/examples simplify parameters
  kratos.gid/apps/Buoyancy/examples/HeatedSquare.tcl
  kratos.gid/apps/CDEM/examples/ContSpheresDrop3D.tcl
  kratos.gid/apps/CDEM/examples/ContinuumDrop2D.tcl
  kratos.gid/apps/ConjugateHeatTransfer/examples/BFS.tcl
  kratos.gid/apps/ConjugateHeatTransfer/examples/HeatedSquare.tcl
  kratos.gid/apps/ConjugateHeatTransfer/examples/cylinder_cooling.tcl
  kratos.gid/apps/ConvectionDiffusion/examples/HeatedSquare.tcl
  kratos.gid/apps/DEM/examples/CirclesDrop.tcl
  kratos.gid/apps/DEM/examples/SpheresDrop.tcl
  kratos.gid/apps/DEMPFEM/examples/InnerSphere.tcl
  kratos.gid/apps/Dam/examples/ThermoMechaDam2D.tcl
  kratos.gid/apps/EmbeddedFluid/examples/CylinderInFlow.tcl
  kratos.gid/apps/FSI/examples/HighRiseBuilding.tcl
  kratos.gid/apps/FSI/examples/MokChannelWithFlexibleWall.tcl
  kratos.gid/apps/FSI/examples/TurekBenchmark.tcl
  kratos.gid/apps/Fluid/examples/CylinderInFlow.tcl
  kratos.gid/apps/Fluid/examples/HighRiseBuilding.tcl
  kratos.gid/apps/FluidDEM/examples/CylinderInFlow.tcl
  kratos.gid/apps/FluidDEM/examples/SpheresDrop.tcl
  kratos.gid/apps/MPM/examples/FallingSandBall.tcl
  kratos.gid/apps/PfemFluid/examples/DamBreakFSI.tcl
  kratos.gid/apps/PfemFluid/examples/WaterDamBreak.tcl
  kratos.gid/apps/PotentialFluid/examples/NACA0012.tcl
  kratos.gid/apps/Structural/examples/HighRiseBuilding.tcl
  kratos.gid/apps/Structural/examples/TrussCantilever.tcl
  kratos.gid/apps/Structural/examples/incompressible_cook_membrane.tcl
  kratos.gid/scripts/Controllers/TreeInjections.tcl
Labels: enhancement

#728 Hotfix/convectiondiffussion submodelpart list
  kratos.gid/apps/ConvectionDiffusion/examples/examples.tcl
  kratos.gid/apps/ConvectionDiffusion/start.tcl
  kratos.gid/apps/ConvectionDiffusion/write/writeProjectParameters.tcl
  kratos.gid/scripts/Writing/WriteMaterials.tcl
  kratos.gid/scripts/Writing/WriteSubModelPart.tcl
  kratos.gid/scripts/Writing/Writing.tcl
Labels: bug

#730 Update the old names of deprecated conditions
  kratos.gid/apps/Buoyancy/xml/XmlController.tcl
  kratos.gid/apps/ConvectionDiffusion/xml/Conditions.xml
Labels: wontfix
