Repository KratosMultiphysics/GiDInterface, pull requests merged in 2022-02, with the labels that each got.

#865 Gid output folder
  kratos.gid/apps/Common/xml/Results.spd
  kratos.gid/scripts/Writing/WriteProjectParameters.tcl
Labels: enhancement

#593 Add time parameters with substepping for structural
  kratos.gid/apps/Common/xml/TimeParametersWithSubstepping.spd
  kratos.gid/apps/Structural/examples/HighRiseBuilding.tcl
  kratos.gid/apps/Structural/examples/TrussCantilever.tcl
  kratos.gid/apps/Structural/write/writeProjectParameters.tcl
  kratos.gid/apps/Structural/xml/SolutionStrategy.spd
  kratos.gid/images/time1.png
  kratos.gid/scripts/Writing/WriteProjectParameters.tcl
  kratos.gid/scripts/Writing/Writing.tcl
Labels: new feature, DO NOT MERGE YET, after release

#857 Fix FluidDem #855
  kratos.gid/apps/DEM/write/write.tcl
  kratos.gid/apps/DEM/write/writeMDPA_Walls.tcl
  kratos.gid/apps/DEM/write/writeProjectParameters.tcl
  kratos.gid/apps/FluidDEM/write/write.tcl
  kratos.gid/apps/FluidDEM/write/writeProjectParameters.tcl
  kratos.gid/scripts/Writing/WriteConditionsByUniqueId.tcl
  kratos.gid/scripts/Writing/WriteProjectParameters.tcl
Labels: bug

#864 [Dam] Customize the DamApplicaiton to use the common Kratos analysis
  kratos.gid/apps/Dam/app.json
  kratos.gid/apps/Dam/write/writeProjectParameters.tcl
  kratos.gid/apps/Dam/xml/Conditions.xml
Labels: enhancement

#823 SwimmingDEM add permeability
  kratos.gid/apps/Fluid/write/write.tcl
  kratos.gid/apps/FluidDEM/write/write.tcl
  kratos.gid/apps/FluidDEM/xml/Elements.xml
  kratos.gid/kratos.tcl
  kratos.gid/scripts/Controllers/TreeInjections.tcl
  kratos.gid/scripts/Utils.tcl
  kratos.gid/scripts/Writing/WriteMaterials.tcl
  kratos.gid/scripts/Writing/WriteProjectParameters.tcl
  kratos.gid/scripts/Writing/Writing.tcl
Labels: enhancement

#739 Feature/add pfem fluid thermic
  kratos.gid/apps/PfemFluid/xml/ModelType.spd
Labels: new feature
