Repository KratosMultiphysics/GiDInterface, pull requests merged in 2022-08, with the labels that each got.

#880 FreeSurface Add initial files
  kratos.gid/apps/Examples/xml/examples.xml
  kratos.gid/apps/Fluid/write/writeProjectParameters.tcl
  kratos.gid/apps/FluidLauncher/start.tcl
  kratos.gid/apps/FreeSurface/app.json
  kratos.gid/apps/FreeSurface/examples/Box.tcl
  kratos.gid/apps/FreeSurface/examples/examples.tcl
  kratos.gid/apps/FreeSurface/examples/examples.xml
  kratos.gid/apps/FreeSurface/images/box2d.png
  kratos.gid/apps/FreeSurface/images/logo.png
  kratos.gid/apps/FreeSurface/start.tcl
  kratos.gid/apps/FreeSurface/write/write.tcl
  kratos.gid/apps/FreeSurface/write/writeProjectParameters.tcl
  kratos.gid/apps/FreeSurface/xml/Conditions.xml
  kratos.gid/apps/FreeSurface/xml/Elements.xml
  kratos.gid/apps/FreeSurface/xml/Main.spd
  kratos.gid/apps/FreeSurface/xml/NodalConditions.xml
  kratos.gid/apps/FreeSurface/xml/Parts.spd
  kratos.gid/apps/FreeSurface/xml/Procs.spd
  kratos.gid/apps/FreeSurface/xml/Strategies.xml
  kratos.gid/apps/FreeSurface/xml/XmlController.tcl
  kratos.gid/kratos_default.spd
  kratos.gid/scripts/Controllers/TreeInjections.tcl
  kratos.gid/scripts/Launch.tcl
  kratos.gid/scripts/Logs.tcl
  kratos.gid/scripts/Writing/WriteProjectParameters.tcl
Labels: new feature

#885 [ConstitutiveLawsApp] Adding more CL to the interface
  kratos.gid/apps/Structural/xml/ConstitutiveLaws.xml
Labels: enhancement

#888 Hotfix linear topologies
  kratos.gid/scripts/Model/Condition.tcl
  kratos.gid/scripts/Model/Element.tcl
  kratos.gid/scripts/Writing/WriteConditions.tcl
  kratos.gid/scripts/Writing/Writing.tcl
Labels: bug
