Repository KratosMultiphysics/GiDInterface, pull requests merged in 2024-07, with the labels that each got.

#982 [Dam] Add new joints to Dam app and remove old ones
  kratos.gid/apps/Dam/write/write.tcl
  kratos.gid/apps/Dam/xml/ConstitutiveLaws.xml
  kratos.gid/apps/Dam/xml/Materials.xml
Labels: enhancement

#983 [Dam] Correct joint constitutive law name
  kratos.gid/apps/Dam/write/write.tcl
  kratos.gid/apps/Dam/xml/ConstitutiveLaws.xml
Labels: bug

#984 [Dam] Add initial joint width to joints and fix problem with tables
  kratos.gid/apps/Dam/examples/ThermoMechaDam2D.tcl
  kratos.gid/apps/Dam/write/write.tcl
  kratos.gid/apps/Dam/write/writeProjectParameters.tcl
  kratos.gid/apps/Dam/xml/Processes.xml
Labels: bug, enhancement

#992 convection diffussion writes as geoms
  kratos.gid/apps/ConvectionDiffusion/app.json
  kratos.gid/apps/ConvectionDiffusion/write/write.tcl
  kratos.gid/apps/ConvectionDiffusion/write/writeProjectParameters.tcl
Labels: enhancement

#989 Embedded migrate geoms
  kratos.gid/apps/CompressibleFluid/app.json
  kratos.gid/apps/CompressibleFluid/write/writeProjectParameters.tcl
  kratos.gid/apps/CompressibleFluid/xml/Conditions.xml
  kratos.gid/apps/EmbeddedFluid/app.json
  kratos.gid/apps/EmbeddedFluid/write/writeProjectParameters.tcl
Labels: enhancement
